import { config } from "dotenv";
config({ path: ".env.local" });
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// Comprehensive English → Spanish translation dictionary
const FULL_NAMES: Record<string, string> = {
  "3/4 sit-up": "Abdominal 3/4",
  "90/90 hamstring": "Estiramiento isquiotibial 90/90",
  "ab crunch machine": "Crunch en máquina",
  "ab roller": "Rueda abdominal",
  "air bike": "Bicicleta al aire",
  "all fours quad stretch": "Estiramiento cuádriceps a cuatro patas",
  "alternate hammer curl": "Curl martillo alterno",
  "alternate incline dumbbell curl": "Curl inclinado alterno con mancuerna",
  "ankle circle": "Círculos de tobillo",
  "anterior tibialis": "Tibial anterior",
  "arm circles": "Círculos de brazos",
  "arnold dumbbell press": "Press Arnold con mancuernas",
  "around the worlds": "Around the Worlds",
  "atlas stones": "Piedras Atlas",
  "back extension": "Extensión de espalda",
  "backward drag": "Arrastre hacia atrás",
  "backward medicine ball throw": "Lanzamiento de balón medicinal hacia atrás",
  "balance board": "Tabla de equilibrio",
  "ball leg curl": "Curl femoral con balón",
  "band hip adductions": "Aducción de cadera con banda",
  "band pull apart": "Separación de banda",
  "barbell ab rollout": "Rueda abdominal con barra",
  "barbell bench press - medium grip": "Press de banca con barra (agarre medio)",
  "barbell curl": "Curl de bíceps con barra",
  "barbell deadlift": "Peso muerto con barra",
  "barbell full squat": "Sentadilla completa con barra",
  "barbell glute bridge": "Puente de glúteo con barra",
  "barbell guillotine bench press": "Press de banca guillotina con barra",
  "barbell hack squat": "Sentadilla hack con barra",
  "barbell hip thrust": "Hip thrust con barra",
  "barbell incline bench press - medium grip": "Press inclinado con barra (agarre medio)",
  "barbell lunge": "Zancada con barra",
  "barbell rear delt row": "Remo deltoides posterior con barra",
  "barbell rollout from bench": "Rueda abdominal desde banco con barra",
  "barbell shoulder press": "Press de hombros con barra",
  "barbell shrug": "Encogimiento de hombros con barra",
  "barbell side bend": "Flexión lateral con barra",
  "barbell squat": "Sentadilla con barra",
  "barbell step ups": "Subidas al cajón con barra",
  "barbell walking lunge": "Zancada caminando con barra",
  "battling ropes": "Cuerdas de batalla",
  "bear crawl": "Gateo de oso",
  "bench dips": "Fondos en banco",
  "bench press": "Press de banca",
  "bent over barbell row": "Remo con barra inclinado",
  "bent over dumbbell rear delt raise": "Elevación posterior con mancuerna inclinado",
  "bent over low-pulley side lateral": "Elevación lateral inclinado en polea baja",
  "bent over two-arm long bar row": "Remo con barra T a dos manos",
  "bent over two-dumbbell row": "Remo con dos mancuernas inclinado",
  "bent-knee hip raise": "Elevación de cadera con rodillas flexionadas",
  "bicycling": "Ciclismo",
  "board press": "Press en tabla",
  "body tricep press": "Press de tríceps corporal",
  "body-up": "Body-Up",
  "bodyweight flyes": "Aperturas con peso corporal",
  "bodyweight walking lunge": "Zancada caminando sin peso",
  "bosu ball crunch": "Crunch en Bosu",
  "bottoms up": "Bottoms Up",
  "box jump (multiple response)": "Saltos al cajón (múltiples)",
  "box squat": "Sentadilla en cajón",
  "brachialis smr": "Liberación miofascial braquial",
  "butt lift (bridge)": "Puente de glúteo",
  "butt-ups": "Elevaciones de glúteo",
  "butterfly": "Mariposa (Pec Deck)",
  "cable chest press": "Press de pecho en polea",
  "cable crossover": "Cruce de poleas",
  "cable crunch": "Crunch en polea",
  "cable deadlift": "Peso muerto en polea",
  "cable hammer curls - rope attachment": "Curl martillo en polea con cuerda",
  "cable hip adduction": "Aducción de cadera en polea",
  "cable internal rotation": "Rotación interna en polea",
  "cable iron cross": "Cruz de hierro en polea",
  "cable judo flip": "Judo Flip en polea",
  "cable lateral raise": "Elevación lateral en polea",
  "cable lying triceps extension": "Extensión de tríceps tumbado en polea",
  "cable one-arm tricep extension": "Extensión de tríceps a un brazo en polea",
  "cable preacher curl": "Curl predicador en polea",
  "cable pull through": "Pull Through en polea",
  "cable rear delt fly": "Apertura posterior en polea",
  "cable reverse crunch": "Crunch inverso en polea",
  "cable rope overhead triceps extension": "Extensión de tríceps sobre cabeza con cuerda",
  "cable rope rear-delt rows": "Remo deltoides posterior con cuerda",
  "cable russian twists": "Giros rusos en polea",
  "cable seated crunch": "Crunch sentado en polea",
  "cable seated lateral raise": "Elevación lateral sentado en polea",
  "cable shoulder press": "Press de hombros en polea",
  "cable shrugs": "Encogimientos de hombros en polea",
  "cable wrist curl": "Curl de muñeca en polea",
  "calf press": "Prensa de gemelos",
  "calf press on the leg press machine": "Prensa de gemelos en máquina",
  "calf raises - seated": "Elevación de talones sentado",
  "calf smr": "Liberación miofascial de gemelo",
  "car drivers": "Conductores de coche",
  "cat stretch": "Estiramiento gato-vaca",
  "chain handle extension": "Extensión con cadena",
  "chair leg extended stretch": "Estiramiento de pierna en silla",
  "chest dip": "Fondo de pecho",
  "chest stretch on stability ball": "Estiramiento de pecho en fitball",
  "child's pose": "Postura del niño",
  "chin-up": "Dominada supina",
  "clean": "Cargada (Clean)",
  "clean and jerk": "Cargada y envión",
  "clean and press": "Cargada y press",
  "clean deadlift": "Peso muerto de cargada",
  "clean from blocks": "Cargada desde bloques",
  "clean pull": "Tirón de cargada",
  "close-grip barbell bench press": "Press de banca agarre cerrado",
  "close-grip dumbbell press": "Press de mancuernas agarre cerrado",
  "close-grip ez bar curl": "Curl barra Z agarre cerrado",
  "close-grip front lat pulldown": "Jalón al pecho agarre cerrado",
  "close-grip standing barbell curl": "Curl de pie con barra agarre cerrado",
  "cobra": "Cobra",
  "cocoons": "Cocoons abdominales",
  "concentration curls": "Curl concentrado",
  "cross-body crunch": "Crunch cruzado",
  "cross body hammer curl": "Curl martillo cruzado",
  "crunches": "Abdominales (Crunch)",
  "crucifix": "Crucifijo",
  "cuban press": "Press cubano",
  "deadlift with bands": "Peso muerto con bandas",
  "decline barbell bench press": "Press declinado con barra",
  "decline close-grip bench to skull crusher": "Press declinado agarre cerrado a rompecráneos",
  "decline crunch": "Crunch declinado",
  "decline dumbbell bench press": "Press declinado con mancuernas",
  "decline dumbbell flyes": "Aperturas declinadas con mancuernas",
  "decline dumbbell triceps extension": "Extensión de tríceps declinado con mancuerna",
  "decline ez bar triceps extension": "Extensión de tríceps declinado con barra Z",
  "decline oblique crunch": "Crunch oblicuo declinado",
  "decline push-up": "Flexiones declinadas",
  "decline reverse crunch": "Crunch inverso declinado",
  "decline smith press": "Press declinado en multipower",
  "deficit deadlift": "Peso muerto en déficit",
  "diamond push-up": "Flexiones diamante",
  "dip machine": "Fondos en máquina",
  "double leg butt kick": "Patada doble a glúteo",
  "drag curl": "Curl de arrastre",
  "drop push": "Drop Push",
  "dumbbell alternate bicep curl": "Curl alterno de bíceps con mancuerna",
  "dumbbell bench press": "Press de banca con mancuernas",
  "dumbbell bench press with neutral grip": "Press de banca con mancuernas agarre neutro",
  "dumbbell bicep curl": "Curl de bíceps con mancuerna",
  "dumbbell clean": "Cargada con mancuerna",
  "dumbbell floor press": "Press en suelo con mancuernas",
  "dumbbell flyes": "Aperturas con mancuernas",
  "dumbbell front raise": "Elevación frontal con mancuerna",
  "dumbbell goblet squat": "Sentadilla goblet con mancuerna",
  "dumbbell incline row": "Remo inclinado con mancuerna",
  "dumbbell lunges": "Zancadas con mancuernas",
  "dumbbell lying one-arm rear lateral raise": "Elevación posterior tumbado a un brazo",
  "dumbbell lying rear lateral raise": "Elevación posterior tumbado con mancuernas",
  "dumbbell lying supination": "Supinación tumbado con mancuerna",
  "dumbbell one-arm shoulder press": "Press de hombro a un brazo con mancuerna",
  "dumbbell one-arm triceps extension": "Extensión de tríceps a un brazo con mancuerna",
  "dumbbell one-arm upright row": "Remo vertical a un brazo con mancuerna",
  "dumbbell prone incline curl": "Curl prono inclinado con mancuerna",
  "dumbbell raise": "Elevación con mancuerna",
  "dumbbell rear lunge": "Zancada reversa con mancuerna",
  "dumbbell scaption": "Scaption con mancuerna",
  "dumbbell seated box jump": "Salto al cajón sentado con mancuerna",
  "dumbbell shoulder press": "Press de hombros con mancuerna",
  "dumbbell shrug": "Encogimiento de hombros con mancuerna",
  "dumbbell side bend": "Flexión lateral con mancuerna",
  "dumbbell squat": "Sentadilla con mancuerna",
  "dumbbell step ups": "Subidas al cajón con mancuerna",
  "dumbbell tricep extension - Loss of a friend": "Extensión de tríceps con mancuerna",
  "dumbbell v-sit cross jab": "V-Sit cross jab con mancuerna",
  "elbow circles": "Círculos de codo",
  "elbow to knee": "Codo a rodilla",
  "elevated cable rows": "Remo elevado en polea",
  "elliptical trainer": "Máquina elíptica",
  "exercise ball crunch": "Crunch en fitball",
  "exercise ball pull-in": "Encogimiento en fitball",
  "external rotation with band": "Rotación externa con banda",
  "ez-bar curl": "Curl con barra Z",
  "ez-bar skullcrusher": "Rompecráneos con barra Z",
  "face pull": "Face Pull",
  "farmer's walk": "Paseo del granjero",
  "finger curls": "Curl de dedos",
  "flat bench cable flyes": "Aperturas en banco plano con polea",
  "flat bench leg pull-in": "Encogimiento de piernas en banco plano",
  "flat bench lying leg raise": "Elevación de piernas en banco plano",
  "floor press": "Press en suelo",
  "flutter kicks": "Patadas de aleteo",
  "foot-smr": "Liberación miofascial de pie",
  "front barbell squat": "Sentadilla frontal con barra",
  "front cable raise": "Elevación frontal en polea",
  "front dumbbell raise": "Elevación frontal con mancuerna",
  "front leg raises": "Elevaciones frontales de pierna",
  "front plate raise": "Elevación frontal con disco",
  "front raise and pullover": "Elevación frontal y pullover",
  "front squat (clean grip)": "Sentadilla frontal (agarre de cargada)",
  "front squats with two kettlebells": "Sentadilla frontal con dos kettlebells",
  "full range-of-motion lat pulldown": "Jalón dorsal rango completo",
  "glute bridge": "Puente de glúteo",
  "glute ham raise": "Elevación glúteo-isquio",
  "glute kickback": "Patada de glúteo",
  "goblet squat": "Sentadilla Goblet",
  "good morning": "Buenos días (Good Morning)",
  "groin and back stretch": "Estiramiento de ingle y espalda",
  "groiners": "Groiners",
  "hack squat": "Sentadilla Hack",
  "hammer curls": "Curl martillo",
  "hamstring stretch": "Estiramiento de isquiotibiales",
  "handstand push-ups": "Flexiones invertidas (pino)",
  "hanging bar good morning": "Buenos días colgado en barra",
  "hanging leg raise": "Elevación de piernas colgado",
  "hanging pike": "Pike colgado",
  "hip circles (prone)": "Círculos de cadera (prono)",
  "hip extension with bands": "Extensión de cadera con bandas",
  "hip flexion with band": "Flexión de cadera con banda",
  "hip stretch": "Estiramiento de cadera",
  "hyperextensions (back extensions)": "Hiperextensiones (extensión de espalda)",
  "iliotibial tract-Loss of a friend stretch": "Estiramiento banda iliotibial",
  "incline barbell bench press": "Press inclinado con barra",
  "incline cable chest fly": "Apertura inclinada en polea",
  "incline cable flye": "Apertura inclinada en polea",
  "incline dumbbell bench press": "Press inclinado con mancuernas",
  "incline dumbbell curl": "Curl inclinado con mancuerna",
  "incline dumbbell flyes": "Aperturas inclinadas con mancuernas",
  "incline dumbbell press": "Press inclinado con mancuernas",
  "incline hammer curls": "Curl martillo inclinado",
  "incline inner biceps curl": "Curl interno inclinado",
  "incline push-up": "Flexiones inclinadas",
  "incline push-up (close grip)": "Flexiones inclinadas agarre cerrado",
  "intermediate groin stretch": "Estiramiento de ingle intermedio",
  "internal rotation with band": "Rotación interna con banda",
  "inverted row": "Remo invertido",
  "iron cross": "Cruz de hierro",
  "isometric chest squeezes": "Apretones isométricos de pecho",
  "isometric neck exercise - front and back": "Ejercicio isométrico de cuello",
  "isometric neck exercise - sides": "Ejercicio isométrico de cuello lateral",
  "isometric wipers": "Limpiadores isométricos",
  "jackknife sit-up": "Abdominal navaja",
  "jerk balance": "Balance de envión",
  "jerk dip squat": "Sentadilla de envión",
  "jogging-treadmill": "Trote en cinta",
  "jumping jacks": "Saltos de tijera",
  "kettlebell clean and press": "Cargada y press con kettlebell",
  "kettlebell dead clean": "Cargada muerta con kettlebell",
  "kettlebell figure 8": "Figura 8 con kettlebell",
  "kettlebell goblet squat": "Sentadilla goblet con kettlebell",
  "kettlebell one-arm row": "Remo a un brazo con kettlebell",
  "kettlebell pistol squat": "Sentadilla pistol con kettlebell",
  "kettlebell sumo deadlift high pull": "Peso muerto sumo tirón alto con kettlebell",
  "kettlebell swing": "Swing con kettlebell",
  "kettlebell thruster": "Thruster con kettlebell",
  "kettlebell turkish get-up (squat style)": "Levantamiento turco con kettlebell",
  "kettlebell windmill": "Molino con kettlebell",
  "kipping muscle up": "Muscle Up con kipping",
  "knee circles": "Círculos de rodilla",
  "knee tuck jump": "Salto con rodillas al pecho",
  "kneeling cable crunch with alternating oblique twists": "Crunch en polea con giros oblicuos alternos",
  "kneeling forearm stretch": "Estiramiento de antebrazo arrodillado",
  "kneeling hip flexor": "Estiramiento flexor de cadera arrodillado",
  "kneeling jump squat": "Sentadilla con salto arrodillado",
  "kneeling squat": "Sentadilla arrodillada",
  "landmine 180s": "Landmine 180 grados",
  "landmine twist": "Giro con landmine",
  "lateral box jump": "Salto lateral al cajón",
  "lateral raise - Loss of a friend in": "Elevación lateral con mancuerna",
  "lat pulldown": "Jalón al pecho",
  "leg extensions": "Extensiones de cuádriceps",
  "leg press": "Prensa de piernas",
  "leg pull-in": "Encogimiento de piernas",
  "leverage chest press": "Press de pecho en máquina",
  "leverage decline chest press": "Press declinado en máquina",
  "leverage high row": "Remo alto en máquina",
  "leverage incline chest press": "Press inclinado en máquina",
  "leverage iso row": "Remo isométrico en máquina",
  "leverage shoulder press": "Press de hombros en máquina",
  "leverage shrug": "Encogimiento en máquina",
  "log lift": "Levantamiento de tronco",
  "low cable crossover": "Cruce de polea baja",
  "low cable tricep extension": "Extensión de tríceps en polea baja",
  "lower back curl": "Curl lumbar",
  "lower back smr": "Liberación miofascial lumbar",
  "lying cable curl": "Curl tumbado en polea",
  "lying close-grip bar curl on high pulley": "Curl tumbado agarre cerrado en polea alta",
  "lying close-grip barbell triceps extension behind the head": "Extensión de tríceps tras nuca tumbado",
  "lying close-grip barbell triceps press": "Press de tríceps tumbado agarre cerrado",
  "lying face down plate neck resistance": "Resistencia de cuello boca abajo con disco",
  "lying face up plate neck resistance": "Resistencia de cuello boca arriba con disco",
  "lying glute": "Estiramiento de glúteo tumbado",
  "lying hamstring curl": "Curl femoral tumbado",
  "lying high bench barbell curl": "Curl con barra en banco alto tumbado",
  "lying leg curls": "Curl femoral tumbado en máquina",
  "lying leg raises": "Elevación de piernas tumbado",
  "lying machine squat": "Sentadilla en máquina tumbado",
  "lying one-arm lateral raise": "Elevación lateral tumbado a un brazo",
  "lying overhead stretch": "Estiramiento sobre cabeza tumbado",
  "lying prone quadriceps": "Estiramiento de cuádriceps prono",
  "lying rear delt raise": "Elevación posterior tumbado",
  "lying straight leg raise": "Elevación de piernas rectas tumbado",
  "lying supine dumbbell curl": "Curl supino con mancuerna",
  "lying t-bar row": "Remo con barra T tumbado",
  "lying triceps press": "Press de tríceps tumbado",
  "machine-assisted pull-up": "Dominadas asistidas en máquina",
  "machine bench press": "Press de banca en máquina",
  "machine bicep curl": "Curl de bíceps en máquina",
  "machine lateral raise": "Elevación lateral en máquina",
  "machine preacher curls": "Curl predicador en máquina",
  "machine shoulder (military) press": "Press militar en máquina",
  "machine squat": "Sentadilla en máquina",
  "machine triceps extension": "Extensión de tríceps en máquina",
  "medicine ball chest pass": "Pase de pecho con balón medicinal",
  "middle back stretch": "Estiramiento de espalda media",
  "monster walk": "Monster Walk con banda",
  "mountain climbers": "Escaladores (Mountain Climbers)",
  "muscle up": "Muscle Up",
  "narrow stance hack squat": "Sentadilla hack agarre estrecho",
  "narrow stance leg press": "Prensa de piernas agarre estrecho",
  "narrow stance squats": "Sentadilla stance estrecho",
  "natural glute ham raise": "Elevación glúteo-isquio natural",
  "neck press": "Press de cuello",
  "oblique crunches": "Crunch oblicuos",
  "oblique crunches - on the floor": "Crunch oblicuos en suelo",
  "one-arm cable laterals": "Elevación lateral a un brazo en polea",
  "one-arm dumbbell bench press": "Press de banca a un brazo con mancuerna",
  "one-arm dumbbell row": "Remo a un brazo con mancuerna",
  "one-arm flat bench dumbbell flye": "Apertura a un brazo en banco plano",
  "one-arm high-pulley cable side bends": "Flexión lateral a un brazo en polea alta",
  "one-arm incline lateral raise": "Elevación lateral inclinada a un brazo",
  "one-arm kettlebell clean and jerk": "Cargada y envión a un brazo con kettlebell",
  "one-arm kettlebell floor press": "Press en suelo a un brazo con kettlebell",
  "one-arm kettlebell push press": "Push Press a un brazo con kettlebell",
  "one-arm kettlebell snatch": "Snatch a un brazo con kettlebell",
  "one-arm kettlebell split jerk": "Split Jerk a un brazo con kettlebell",
  "one-arm kettlebell split snatch": "Split Snatch a un brazo con kettlebell",
  "one-arm kettlebell swings": "Swing a un brazo con kettlebell",
  "one-arm lat pulldown": "Jalón a un brazo",
  "one-arm long bar row": "Remo a un brazo con barra T",
  "one-arm medicine ball slam": "Slam de balón medicinal a un brazo",
  "one-arm side deadlift": "Peso muerto lateral a un brazo",
  "one-arm side laterals": "Elevación lateral a un brazo",
  "one-knee to chest": "Una rodilla al pecho",
  "open palm push": "Empuje con palma abierta",
  "otis-up": "Otis-Up",
  "overhead cable curl": "Curl sobre cabeza en polea",
  "overhead lat": "Estiramiento dorsal sobre cabeza",
  "overhead slam": "Slam sobre cabeza",
  "overhead squat": "Sentadilla sobre cabeza",
  "overhead stretch": "Estiramiento sobre cabeza",
  "overhead triceps": "Estiramiento tríceps sobre cabeza",
  "pallof press with rotation": "Pallof Press con rotación",
  "palms-down dumbbell wrist curl over a bench": "Curl de muñeca palmas abajo con mancuerna",
  "palms-down wrist curl over a bench": "Curl de muñeca palmas abajo en banco",
  "palms-up barbell wrist curl over a bench": "Curl de muñeca palmas arriba con barra",
  "palms-up dumbbell wrist curl over a bench": "Curl de muñeca palmas arriba con mancuerna",
  "parallel bar dip": "Fondos en paralelas",
  "pelvic tilt into bridge": "Báscula pélvica a puente",
  "peroneals-Loss of a friend stretch": "Estiramiento de peroneos",
  "physioball hip bridge": "Puente de cadera en fitball",
  "pin presses": "Press con topes",
  "plank": "Plancha",
  "plate pinch": "Pinza con disco",
  "platform hamstring slides": "Deslizamiento de isquiotibiales",
  "plie dumbbell squat": "Sentadilla plié con mancuerna",
  "plyo kettlebell pushups": "Flexiones pliométricas con kettlebell",
  "plyo push-up": "Flexiones pliométricas",
  "pocket swings": "Pocket Swings",
  "power clean": "Power Clean",
  "power clean from blocks": "Power Clean desde bloques",
  "power jerk": "Power Jerk",
  "power partials": "Parciales de potencia",
  "power snatch": "Power Snatch",
  "power snatch from blocks": "Power Snatch desde bloques",
  "power stairs": "Escaleras de potencia",
  "preacher curl": "Curl predicador",
  "preacher hammer dumbbell curl": "Curl martillo predicador con mancuerna",
  "press sit-up": "Abdominal con press",
  "prone manual hamstring": "Isquiotibial manual prono",
  "prowler sprint": "Sprint con trineo",
  "pull through": "Pull Through",
  "pullups": "Dominadas",
  "push press": "Push Press",
  "push press - behind the neck": "Push Press tras nuca",
  "push-up (close and wide hand positions)": "Flexiones (manos juntas y separadas)",
  "push-ups": "Flexiones",
  "push-ups - Loss of a friend on knees": "Flexiones de rodillas",
  "push-ups with feet elevated": "Flexiones con pies elevados",
  "push-ups with feet on an exercise ball": "Flexiones con pies en fitball",
  "pushups (close and wide hand positions)": "Flexiones (agarre cerrado y abierto)",
  "quad stretch": "Estiramiento de cuádriceps",
  "rack delivery": "Entrega en rack",
  "rack pull": "Rack Pull",
  "rack pulls with bands": "Rack Pull con bandas",
  "rear leg raises": "Elevaciones de pierna trasera",
  "recumbent bike": "Bicicleta reclinada",
  "reverse band bench press": "Press de banca con banda invertida",
  "reverse band box squat": "Sentadilla en cajón con banda invertida",
  "reverse band deadlift": "Peso muerto con banda invertida",
  "reverse barbell curl": "Curl invertido con barra",
  "reverse cable curl": "Curl invertido en polea",
  "reverse crunch": "Crunch inverso",
  "reverse flyes": "Aperturas inversas",
  "reverse flyes with external rotation": "Aperturas inversas con rotación externa",
  "reverse grip bent-over rows": "Remo inclinado agarre invertido",
  "reverse grip triceps pushdown": "Extensión de tríceps agarre invertido",
  "reverse machine flyes": "Aperturas inversas en máquina",
  "reverse plate curls": "Curl invertido con disco",
  "reverse triceps bench press": "Press de tríceps invertido en banco",
  "ring dips": "Fondos en anillas",
  "rocket jump": "Salto cohete",
  "rocking standing calf raise": "Elevación de talones balanceada",
  "romanian deadlift": "Peso muerto rumano",
  "romanian deadlift from deficit": "Peso muerto rumano en déficit",
  "rope climbing": "Escalada de cuerda",
  "rope crunch": "Crunch con cuerda",
  "rope jumping": "Saltar la cuerda",
  "rope straight-arm pulldown": "Jalón con brazos rectos con cuerda",
  "round-the-clock push-up": "Flexiones reloj",
  "rowing, stationary": "Remo estacionario",
  "runner's stretch": "Estiramiento de corredor",
  "running, treadmill": "Carrera en cinta",
  "russian twist": "Giro ruso",
  "sandbag load": "Carga de saco",
  "scapular pull-up": "Dominada escapular",
  "scissor jump": "Salto tijera",
  "scissors": "Tijeras",
  "seated band hamstring curl": "Curl femoral sentado con banda",
  "seated barbell military press": "Press militar sentado con barra",
  "seated barbell twist": "Giro sentado con barra",
  "seated bent-over one-arm dumbbell triceps extension": "Extensión de tríceps inclinado sentado a un brazo",
  "seated bent-over rear delt raise": "Elevación posterior inclinado sentado",
  "seated cable rows": "Remo sentado en polea",
  "seated calf raise": "Elevación de talones sentado",
  "seated close-grip concentration barbell curl": "Curl concentrado sentado agarre cerrado",
  "seated dumbbell curl": "Curl sentado con mancuerna",
  "seated dumbbell inner biceps curl": "Curl interno sentado con mancuerna",
  "seated dumbbell palms-down wrist curl": "Curl de muñeca palmas abajo sentado",
  "seated dumbbell palms-up wrist curl": "Curl de muñeca palmas arriba sentado",
  "seated flat bench leg pull-in": "Encogimiento de piernas sentado en banco",
  "seated floor hamstring stretch": "Estiramiento de isquiotibiales sentado en suelo",
  "seated glute": "Estiramiento de glúteo sentado",
  "seated head harness neck resistance": "Resistencia de cuello sentado con arnés",
  "seated leg curl": "Curl femoral sentado",
  "seated leg tucks": "Encogimientos de piernas sentado",
  "seated one-arm dumbbell palms-down wrist curl": "Curl de muñeca a un brazo palmas abajo sentado",
  "seated overhead stretch": "Estiramiento sobre cabeza sentado",
  "seated palm-up barbell wrist curl": "Curl de muñeca palmas arriba sentado con barra",
  "seated side lateral raise": "Elevación lateral sentado",
  "seated triceps press": "Press de tríceps sentado",
  "seated two-arm palms-up low-pulley wrist curl": "Curl de muñeca en polea baja sentado",
  "shotgun row": "Remo Shotgun",
  "shoulder press - Loss of a friend with bands": "Press de hombros con bandas",
  "shoulder stretch": "Estiramiento de hombro",
  "side bridge": "Puente lateral",
  "side lateral raise": "Elevación lateral",
  "side lying groin stretch": "Estiramiento de ingle lateral",
  "side lunge": "Zancada lateral",
  "side neck stretch": "Estiramiento lateral de cuello",
  "side plank": "Plancha lateral",
  "side standing long jump": "Salto largo lateral",
  "side wrist pull": "Tirón lateral de muñeca",
  "side-lying floor stretch": "Estiramiento lateral en suelo",
  "single-arm cable crossover": "Cruce de polea a un brazo",
  "single-arm linear jammer": "Jammer lineal a un brazo",
  "single-arm push-up": "Flexión a un brazo",
  "single leg bridge": "Puente a una pierna",
  "single leg butt kick": "Patada a glúteo a una pierna",
  "single leg calf raise": "Elevación de talón a una pierna",
  "single leg deadlift": "Peso muerto a una pierna",
  "single leg glute bridge": "Puente de glúteo a una pierna",
  "single leg leg extension": "Extensión de cuádriceps a una pierna",
  "single leg low box squat": "Sentadilla en cajón bajo a una pierna",
  "single leg push-off": "Impulso a una pierna",
  "single leg squat": "Sentadilla a una pierna",
  "single leg split squat": "Sentadilla búlgara",
  "sit-up": "Abdominal (Sit-Up)",
  "sit squats": "Sentadilla en silla",
  "skating": "Patinaje",
  "sled drag - Loss of a friend forward": "Arrastre de trineo hacia delante",
  "sled push": "Empuje de trineo",
  "sledgehammer swings": "Golpes con mazo",
  "smith incline bench press": "Press inclinado en multipower",
  "smith machine behind the back shrug": "Encogimiento tras espalda en multipower",
  "smith machine bench press": "Press de banca en multipower",
  "smith machine bent over row": "Remo inclinado en multipower",
  "smith machine calf raise": "Elevación de talones en multipower",
  "smith machine close-grip bench press": "Press agarre cerrado en multipower",
  "smith machine decline press": "Press declinado en multipower",
  "smith machine hang power clean": "Power Clean colgante en multipower",
  "smith machine hip raise": "Elevación de cadera en multipower",
  "smith machine incline bench press": "Press inclinado en multipower",
  "smith machine leg press": "Prensa de piernas en multipower",
  "smith machine one-arm upright row": "Remo vertical a un brazo en multipower",
  "smith machine overhead press": "Press sobre cabeza en multipower",
  "smith machine pistol squat": "Sentadilla pistol en multipower",
  "smith machine reverse calf raises": "Elevación de talones invertida en multipower",
  "smith machine squat": "Sentadilla en multipower",
  "smith machine stiff-legged deadlift": "Peso muerto piernas rígidas en multipower",
  "smith machine upright row": "Remo vertical en multipower",
  "smith single-leg split squat": "Sentadilla búlgara en multipower",
  "snatch": "Arrancada (Snatch)",
  "snatch pull": "Tirón de arrancada",
  "snatch shrug": "Encogimiento de arrancada",
  "speed band overhead triceps": "Extensión tríceps sobre cabeza con banda",
  "speed box squat": "Sentadilla en cajón de velocidad",
  "speed squats": "Sentadillas de velocidad",
  "spell caster": "Lanzahechizos",
  "spider crawl": "Gateo araña",
  "spider curl": "Curl araña",
  "spinal stretch": "Estiramiento espinal",
  "split snatch": "Split Snatch",
  "split squats": "Sentadillas divididas",
  "squat jerk": "Jerk en sentadilla",
  "squat with bands": "Sentadilla con bandas",
  "squat with chains": "Sentadilla con cadenas",
  "squats - with bodyweight": "Sentadilla con peso corporal",
  "stairmaster": "Escaladora",
  "standing alternating dumbbell press": "Press alterno de pie con mancuerna",
  "standing barbell calf raise": "Elevación de talones con barra",
  "standing barbell press behind neck": "Press tras nuca con barra",
  "standing bent-over one-arm dumbbell triceps extension": "Extensión tríceps inclinado a un brazo",
  "standing bent-over two-arm dumbbell triceps extension": "Extensión tríceps inclinado a dos brazos",
  "standing biceps cable curl": "Curl de bíceps de pie en polea",
  "standing biceps stretch": "Estiramiento de bíceps de pie",
  "standing cable chest press": "Press de pecho de pie en polea",
  "standing cable lift": "Elevación de pie en polea",
  "standing cable wood chop": "Leñador en polea",
  "standing calf raises": "Elevación de talones de pie",
  "standing concentration curl": "Curl concentrado de pie",
  "standing dumbbell calf raise": "Elevación de talones con mancuerna",
  "standing dumbbell press": "Press de pie con mancuernas",
  "standing dumbbell reverse curl": "Curl invertido de pie con mancuerna",
  "standing dumbbell straight-arm front delt raise above head": "Elevación frontal de pie sobre cabeza",
  "standing dumbbell triceps extension": "Extensión de tríceps de pie con mancuerna",
  "standing dumbbell upright row": "Remo vertical de pie con mancuerna",
  "standing elevated quad stretch": "Estiramiento de cuádriceps elevado",
  "standing front barbell raise over head": "Elevación frontal con barra sobre cabeza",
  "standing gastrocnemius calf stretch": "Estiramiento de gastrocnemio de pie",
  "standing hamstring and calf stretch": "Estiramiento de isquiotibiales y gemelos de pie",
  "standing hip circles": "Círculos de cadera de pie",
  "standing hip extension": "Extensión de cadera de pie",
  "standing inner-biceps curl": "Curl interno de pie",
  "standing lat stretch": "Estiramiento dorsal de pie",
  "standing leg curl": "Curl femoral de pie",
  "standing long jump": "Salto de longitud",
  "standing low-pulley deltoid raise": "Elevación de deltoides en polea baja",
  "standing low-pulley one-arm triceps extension": "Extensión tríceps a un brazo en polea baja",
  "standing military press": "Press militar de pie",
  "standing olympic plate hand squeeze": "Apretón de disco olímpico",
  "standing one-arm cable curl": "Curl a un brazo en polea de pie",
  "standing one-arm dumbbell curl over incline bench": "Curl a un brazo sobre banco inclinado",
  "standing one-arm dumbbell triceps extension": "Extensión tríceps a un brazo de pie",
  "standing overhead barbell triceps extension": "Extensión tríceps sobre cabeza con barra",
  "standing palm-in one-arm dumbbell press": "Press de un brazo palma adentro de pie",
  "standing pelvic tilt": "Báscula pélvica de pie",
  "standing soleus and achilles stretch": "Estiramiento de sóleo y aquiles",
  "standing toe touches": "Tocar puntas de los pies de pie",
  "standing towel triceps extension": "Extensión tríceps con toalla de pie",
  "standing two-arm overhead throw": "Lanzamiento sobre cabeza a dos brazos",
  "step mill": "Step Mill",
  "stiff leg barbell good morning": "Buenos días con piernas rígidas y barra",
  "stiff-legged barbell deadlift": "Peso muerto piernas rígidas con barra",
  "stiff-legged dumbbell deadlift": "Peso muerto piernas rígidas con mancuerna",
  "stomach vacuum": "Vacío abdominal",
  "straight-arm dumbbell pullover": "Pullover con mancuerna brazos rectos",
  "straight-arm pulldown": "Jalón con brazos rectos",
  "straight bar bench mid rows": "Remo medio en banco con barra recta",
  "stretch lying down": "Estiramiento tumbado",
  "sumo deadlift": "Peso muerto sumo",
  "sumo deadlift with bands": "Peso muerto sumo con bandas",
  "superman": "Superman",
  "supine chest throw": "Lanzamiento de pecho supino",
  "supine one-arm overhead throw": "Lanzamiento sobre cabeza supino a un brazo",
  "suspended push-up": "Flexión suspendida",
  "suspended reverse crunch": "Crunch inverso suspendido",
  "suspended row": "Remo suspendido",
  "suspended split squat": "Sentadilla búlgara suspendida",
  "t-bar row with handle": "Remo en barra T con asa",
  "thigh abductor": "Abducción de cadera",
  "thigh adductor": "Aducción de cadera",
  "tire flip": "Volteo de neumático",
  "toe touchers": "Toque de puntas",
  "torso rotation": "Rotación de torso",
  "trail running/walking": "Trail running/caminata",
  "trap bar deadlift": "Peso muerto con barra hexagonal",
  "tricep dumbbell kickback": "Patada de tríceps con mancuerna",
  "tricep side stretch": "Estiramiento lateral de tríceps",
  "triceps overhead extension with rope": "Extensión tríceps sobre cabeza con cuerda",
  "triceps pushdown": "Extensión de tríceps en polea",
  "triceps pushdown - v-bar attachment": "Extensión tríceps con barra V",
  "triceps stretch": "Estiramiento de tríceps",
  "tuck crunch": "Crunch encogido",
  "two-arm dumbbell preacher curl": "Curl predicador con dos mancuernas",
  "two-arm kettlebell clean": "Cargada con dos kettlebells",
  "two-arm kettlebell jerk": "Jerk con dos kettlebells",
  "two-arm kettlebell military press": "Press militar con dos kettlebells",
  "two-arm kettlebell row": "Remo con dos kettlebells",
  "upright barbell row": "Remo vertical con barra",
  "upright cable row": "Remo vertical en polea",
  "upright row - with bands": "Remo vertical con bandas",
  "upward stretch": "Estiramiento hacia arriba",
  "v-bar pulldown": "Jalón con barra V",
  "v-bar pullup": "Dominada con barra V",
  "walking, treadmill": "Caminata en cinta",
  "weighted ball hyperextension": "Hiperextensión con balón",
  "weighted ball side bend": "Flexión lateral con balón",
  "weighted bench dip": "Fondos en banco con peso",
  "weighted crunches": "Crunch con peso",
  "weighted jump squat": "Sentadilla con salto y peso",
  "weighted pull-ups": "Dominadas con peso",
  "weighted sit-ups - with bands": "Abdominales con peso y bandas",
  "weighted squat": "Sentadilla con peso",
  "wide stance barbell squat": "Sentadilla amplia con barra",
  "wide stance stiff legs": "Peso muerto piernas rígidas stance amplio",
  "wide-grip barbell curl": "Curl agarre ancho con barra",
  "wide-grip decline barbell bench press": "Press declinado agarre ancho",
  "wide-grip decline barbell pullover": "Pullover declinado agarre ancho",
  "wide-grip lat pulldown": "Jalón al pecho agarre ancho",
  "wide-grip pulldown behind the neck": "Jalón tras nuca agarre ancho",
  "wide-grip rear pull-up": "Dominada posterior agarre ancho",
  "wide-grip standing barbell curl": "Curl de pie agarre ancho con barra",
  "windmills": "Molinos",
  "world's greatest stretch": "World's Greatest Stretch",
  "wrist circles": "Círculos de muñeca",
  "wrist roller": "Rodillo de muñeca",
  "wrist rotations with straight bar": "Rotaciones de muñeca con barra",
  "zercher squats": "Sentadilla Zercher",
  "zottman curl": "Curl Zottman",
  "zottman preacher curl": "Curl Zottman predicador",
};

async function main() {
  console.log("=== Translate exercises to Spanish ===\n");

  // Fetch all exercises without name_es
  const { data: exercises, error } = await supabase
    .from("exercises")
    .select("id, name")
    .is("name_es", null);

  if (error) {
    console.error("Error:", error.message);
    process.exit(1);
  }

  console.log(`Found ${exercises?.length ?? 0} exercises without Spanish name.\n`);
  if (!exercises || exercises.length === 0) return;

  let updated = 0;
  let skipped = 0;

  for (const ex of exercises) {
    const nameEs = FULL_NAMES[ex.name.toLowerCase()];
    if (!nameEs) {
      skipped++;
      continue;
    }

    const { error: updateErr } = await supabase
      .from("exercises")
      .update({ name_es: nameEs })
      .eq("id", ex.id);

    if (updateErr) {
      console.error(`  Error updating "${ex.name}": ${updateErr.message}`);
    } else {
      updated++;
    }

    if ((updated + skipped) % 100 === 0) {
      console.log(`  Progress: ${updated + skipped}/${exercises.length} | Updated: ${updated} | No translation: ${skipped}`);
    }
  }

  console.log(`\n========= TRANSLATION COMPLETE =========`);
  console.log(`Total without name_es: ${exercises.length}`);
  console.log(`Updated:               ${updated}`);
  console.log(`No translation found:  ${skipped}`);
  console.log(`========================================`);
}

main().catch(console.error);
